//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Worx_ELogisticsEntities : DbContext
    {
        public Worx_ELogisticsEntities()
            : base("name=Worx_ELogisticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Wrx_Commodity> Wrx_Commodity { get; set; }
        public virtual DbSet<Wrx_Containers> Wrx_Containers { get; set; }
        public virtual DbSet<Wrx_ContainerTypes> Wrx_ContainerTypes { get; set; }
        public virtual DbSet<Wrx_Continents> Wrx_Continents { get; set; }
        public virtual DbSet<Wrx_Countries> Wrx_Countries { get; set; }
        public virtual DbSet<Wrx_CropYear> Wrx_CropYear { get; set; }
        public virtual DbSet<Wrx_Customers> Wrx_Customers { get; set; }
        public virtual DbSet<Wrx_Destination> Wrx_Destination { get; set; }
        public virtual DbSet<Wrx_DocumentTerms> Wrx_DocumentTerms { get; set; }
        public virtual DbSet<Wrx_DTHC> Wrx_DTHC { get; set; }
        public virtual DbSet<Wrx_FCL> Wrx_FCL { get; set; }
        public virtual DbSet<Wrx_Grade> Wrx_Grade { get; set; }
        public virtual DbSet<Wrx_Main> Wrx_Main { get; set; }
        public virtual DbSet<Wrx_ManyMany> Wrx_ManyMany { get; set; }
        public virtual DbSet<Wrx_Origin> Wrx_Origin { get; set; }
        public virtual DbSet<Wrx_Ports> Wrx_Ports { get; set; }
        public virtual DbSet<Wrx_SecurityLevel> Wrx_SecurityLevel { get; set; }
        public virtual DbSet<Wrx_SendingBank> Wrx_SendingBank { get; set; }
        public virtual DbSet<Wrx_ServcieType> Wrx_ServcieType { get; set; }
        public virtual DbSet<Wrx_Teams> Wrx_Teams { get; set; }
        public virtual DbSet<Wrx_Transloaders> Wrx_Transloaders { get; set; }
        public virtual DbSet<Wrx_Units> Wrx_Units { get; set; }
        public virtual DbSet<Wrx_User> Wrx_User { get; set; }
        public virtual DbSet<Wrx_Company> Wrx_Company { get; set; }
        public virtual DbSet<Wrx_DocumentationTracking> Wrx_DocumentationTracking { get; set; }
        public virtual DbSet<Wrx_RailCars> Wrx_RailCars { get; set; }
        public virtual DbSet<Wrx_SalesContract> Wrx_SalesContract { get; set; }
    }
}
