//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesAndAttachement
    {
        public long NotesID { get; set; }
        public string Subject { get; set; }
        public string EntityID { get; set; }
        public string MimeType { get; set; }
        public string Base64File { get; set; }
        public string FileName { get; set; }
        public string Notes { get; set; }
        public string OwnerId { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> CratedOn { get; set; }
    }
}
