//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_SalesContractMaster
    {
        public Nullable<System.DateTime> Contractdate { get; set; }
        public string Contractnumber { get; set; }
        public string CmpName { get; set; }
        public string Termsofpayment { get; set; }
        public string Itemnumber { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Portdischarge { get; set; }
        public string ORIGINVARIETY { get; set; }
        public string Grade { get; set; }
        public string Site { get; set; }
        public string Warehouse { get; set; }
        public string Buyer { get; set; }
        public string Ordertype { get; set; }
        public Nullable<System.DateTime> Deliveryfromdate { get; set; }
        public Nullable<System.DateTime> Deliverytodate { get; set; }
        public string Deliveryterms { get; set; }
        public string Unit { get; set; }
        public string Currency { get; set; }
        public string Payment { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<long> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public long id { get; set; }
    }
}
