//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_SalesTrans
    {
        public string Contractnumber { get; set; }
        public string Contractdate { get; set; }
        public string Configuration { get; set; }
        public string Contractstatus { get; set; }
        public string ORIGINVARIETY { get; set; }
        public string Grade { get; set; }
        public string Site { get; set; }
        public string WareHouse { get; set; }
        public string SPOrder { get; set; }
        public string Itemnumber { get; set; }
        public string Buyer { get; set; }
        public string CmpName { get; set; }
        public string CommisionGroup { get; set; }
        public string Ordertype { get; set; }
        public string Deliveryfromdate { get; set; }
        public string Deliverytodate { get; set; }
        public string Deliveryterms { get; set; }
        public string Portofloading { get; set; }
        public string Portdischarge { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Cquantity { get; set; }
        public Nullable<double> Squantity { get; set; }
        public string Numberofbags { get; set; }
        public string Currency { get; set; }
        public string Price { get; set; }
        public string Payment { get; set; }
        public Nullable<double> Speriod { get; set; }
        public string VesselName { get; set; }
        public string Billoflading { get; set; }
        public string InvoiceAcc { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public Nullable<double> PaymentRec { get; set; }
        public Nullable<System.DateTime> Paymentdate { get; set; }
        public Nullable<double> Outstanding { get; set; }
        public string AccStatus { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<long> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<System.DateTime> ownedon { get; set; }
        public Nullable<long> ownedby { get; set; }
        public long id { get; set; }
    }
}
