//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_ShipBooking
    {
        public long id { get; set; }
        public string BookingRef { get; set; }
        public string ShippingLine { get; set; }
        public string FCLNum { get; set; }
        public Nullable<System.DateTime> DoxCutoff { get; set; }
        public Nullable<System.DateTime> VGMCutoff { get; set; }
        public Nullable<System.DateTime> LRD { get; set; }
        public Nullable<System.DateTime> ETS { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string VesselName { get; set; }
        public string VoyageNum { get; set; }
        public Nullable<System.DateTime> ERD { get; set; }
        public string SplitNum { get; set; }
        public Nullable<long> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<long> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
    }
}
