//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_Dox
    {
        public long id { get; set; }
        public string BLNo { get; set; }
        public Nullable<System.DateTime> BLDate { get; set; }
        public string DTHC { get; set; }
        public Nullable<long> FreeDays { get; set; }
        public Nullable<long> B13No { get; set; }
        public Nullable<System.DateTime> B13Date { get; set; }
        public string B13Value { get; set; }
        public string FreightValue { get; set; }
        public string BLISent { get; set; }
        public string BLDraftReceived { get; set; }
        public string Appropriation { get; set; }
        public string BLApproval { get; set; }
        public string OBLReceived { get; set; }
        public string WQrequest { get; set; }
        public string WQDraftReceived { get; set; }
        public string WQDraftApproval { get; set; }
        public string OriginalWQReceived { get; set; }
        public string Phytorequest { get; set; }
        public string PhytoDraftReceived { get; set; }
        public string PhytoDraftApproval { get; set; }
        public string OriginalPhytoReceived { get; set; }
        public string COODraftReceived { get; set; }
        public string COODraftApproval { get; set; }
        public string COOPhytoReceived { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public string InsuranceValue { get; set; }
        public string InsurancecetificateNo { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
    }
}
