//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_RailCarMap
    {
        public int id { get; set; }
        public Nullable<int> RailCarid { get; set; }
        public Nullable<int> Pkageid { get; set; }
        public string containerid { get; set; }
        public Nullable<double> Tonnage { get; set; }
        public Nullable<double> sealno { get; set; }
        public Nullable<int> bookingid { get; set; }
        public string VGM { get; set; }
        public Nullable<System.DateTime> Shipdate { get; set; }
        public Nullable<System.DateTime> Expiredate { get; set; }
        public Nullable<double> balancetomap { get; set; }
        public Nullable<int> Splitno { get; set; }
        public Nullable<int> contractid { get; set; }
    }
}
