//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_Main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wrx_Main()
        {
            this.Wrx_DocumentationTracking = new HashSet<Wrx_DocumentationTracking>();
        }
    
        public Nullable<System.DateTime> Contract_date { get; set; }
        public string Through { get; set; }
        public string Contract_number { get; set; }
        public string Name { get; set; }
        public string Terms_of_payment { get; set; }
        public string Item_number { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Port_Place_of_discharge { get; set; }
        public string Port_Place_of_loading { get; set; }
        public string Reference_number { get; set; }
        public string ORIGIN_VARIETY { get; set; }
        public string Grade { get; set; }
        public string Site { get; set; }
        public string Warehouse { get; set; }
        public string Buyer__ { get; set; }
        public string Order_type { get; set; }
        public Nullable<System.DateTime> Delivery_from_date { get; set; }
        public Nullable<System.DateTime> Delivery_to_date { get; set; }
        public string Delivery_terms { get; set; }
        public string Unit { get; set; }
        public Nullable<double> Contract_quantity { get; set; }
        public string Currency { get; set; }
        public string Payment { get; set; }
        public Nullable<bool> Closed { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wrx_DocumentationTracking> Wrx_DocumentationTracking { get; set; }
    }
}
