//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_Containers
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LoadingDate { get; set; }
        public Nullable<int> RailCar { get; set; }
        public string BookingNum { get; set; }
        public string LoadOrderNumber { get; set; }
        public string ContainerNum { get; set; }
        public string NumOfPackages { get; set; }
        public string SealNumber { get; set; }
        public double UnloadWeight { get; set; }
        public double BagWeight { get; set; }
        public string TransferOrderNum { get; set; }
        public int ContractBarNumber { get; set; }
        public Nullable<double> VGM { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
