//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_Packages
    {
        public int id { get; set; }
        public string bagname { get; set; }
        public Nullable<int> bagtype { get; set; }
        public Nullable<double> bagweight { get; set; }
        public Nullable<int> weightunit { get; set; }
        public string colour { get; set; }
        public Nullable<bool> plain { get; set; }
        public string Dimensions { get; set; }
        public Nullable<double> MTConversion { get; set; }
        public string image { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
    }
}
