//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_Commodity
    {
        public string id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Botanical { get; set; }
        public string Levy { get; set; }
        public Nullable<bool> status { get; set; }
        public string image { get; set; }
    }
}
