//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_DocumentationTracking
    {
        public int ID { get; set; }
        public Nullable<int> DocSpecialist { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<int> Bar { get; set; }
        public string DeliveryTerm { get; set; }
        public Nullable<int> DocumentTerm { get; set; }
        public Nullable<int> DTHC { get; set; }
        public string NotifyParty { get; set; }
        public string IECCode { get; set; }
        public string CustomerName { get; set; }
        public string Comment { get; set; }
        public string Booking { get; set; }
        public Nullable<int> PortOfLoading { get; set; }
        public string PortOfDestination { get; set; }
        public string CountryOfDestination { get; set; }
        public Nullable<System.DateTime> SailingDate { get; set; }
        public Nullable<System.DateTime> ActualSailingDate { get; set; }
        public Nullable<System.DateTime> OriginalDocDueForSending { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<int> NumOfFCL { get; set; }
        public string ShippmentType { get; set; }
        public Nullable<int> NumOfCars { get; set; }
        public string LotNumber { get; set; }
        public string Commodity { get; set; }
        public string Grade { get; set; }
        public Nullable<double> InvoiceQTY { get; set; }
        public Nullable<decimal> Price_MT { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public string InvoiceAmountInWords { get; set; }
        public string ERPInvoiceNO { get; set; }
        public string B13orAESFilingNumber { get; set; }
        public Nullable<double> B13orAESFilingAmount { get; set; }
        public string DescriptionofProduct { get; set; }
        public Nullable<int> CropYear { get; set; }
        public string ProductionMonth { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public Nullable<System.DateTime> BLISentDate { get; set; }
        public Nullable<System.DateTime> ApropriationDate { get; set; }
        public string BLNO { get; set; }
        public Nullable<System.DateTime> BLApprovalDate { get; set; }
        public Nullable<System.DateTime> BLFreightInvoiceReceivedDate { get; set; }
        public Nullable<System.DateTime> PhytoRequestedDate { get; set; }
        public Nullable<System.DateTime> PhytoReceivedDate { get; set; }
        public Nullable<System.DateTime> SGSRequestedDate { get; set; }
        public Nullable<System.DateTime> SGS_Received_Date { get; set; }
        public Nullable<System.DateTime> COOReceiveDate { get; set; }
        public Nullable<System.DateTime> USPhytoRequestedDate { get; set; }
        public Nullable<System.DateTime> USPhytoReceivedDate { get; set; }
        public Nullable<System.DateTime> DateFinaldocsetsent { get; set; }
        public Nullable<bool> InhouseFF { get; set; }
        public string Status { get; set; }
        public string ToBankBuyer { get; set; }
        public string SendingBank { get; set; }
        public string ReceivingBank { get; set; }
        public string BankReference { get; set; }
        public string Courier { get; set; }
        public string AWBOriginaldocsweresent { get; set; }
        public string Freightinvoice { get; set; }
        public Nullable<double> FreightinvoiceAmount { get; set; }
        public string Vessel { get; set; }
        public string ShippingLine { get; set; }
        public string ContractBar { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> NumberofDays { get; set; }
        public Nullable<System.DateTime> ERPInvoiceDate { get; set; }
        public Nullable<System.DateTime> PaymentRcvdDate { get; set; }
        public Nullable<double> PaymentRcvdAmt { get; set; }
        public string MISC { get; set; }
        public Nullable<int> NumberofBags { get; set; }
        public string OnBehalfOf { get; set; }
        public Nullable<decimal> Add1 { get; set; }
        public Nullable<decimal> Add2 { get; set; }
        public Nullable<decimal> Less1 { get; set; }
        public Nullable<decimal> Less2 { get; set; }
        public string ConsigneeText { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeFax { get; set; }
        public string ConsigneeEmail { get; set; }
        public string PaymTerm { get; set; }
        public string ImportPermit { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Wrx_PurchaseContractsMaster Wrx_PurchaseContractsMaster { get; set; }
    }
}
