//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_RailCars
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string Number { get; set; }
        public string Commodity { get; set; }
        public string Grade { get; set; }
        public double LoadWEIGHT { get; set; }
        public Nullable<int> ORIGIN { get; set; }
        public Nullable<int> DESTINATION { get; set; }
        public string TRANSFERJOURNALNum { get; set; }
        public string TRANSFERORDERNum { get; set; }
        public string BAGS { get; set; }
        public string CFIACourierNumber { get; set; }
        public string SGSCourierNumber { get; set; }
        public Nullable<double> Invoiced { get; set; }
        public string Charges { get; set; }
        public string BLNum { get; set; }
        public string Comments { get; set; }
        public string CFIA { get; set; }
        public Nullable<System.DateTime> UnloadDate { get; set; }
        public string BookingNum { get; set; }
        public string MovementNum { get; set; }
        public Nullable<bool> SGS { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<double> UnloadWEIGHT { get; set; }
        public Nullable<double> TempStuffWEIGHT { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
