//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_ProdInstruct
    {
        public long id { get; set; }
        public Nullable<long> Plant { get; set; }
        public Nullable<int> UnitType { get; set; }
        public Nullable<int> UnitNum { get; set; }
        public Nullable<int> BagsNum { get; set; }
        public Nullable<int> UnitMesure { get; set; }
        public Nullable<double> TotalMT { get; set; }
        public string CFIA { get; set; }
        public string SGS { get; set; }
        public string Tags { get; set; }
        public string Crop { get; set; }
        public string Loadinstructions { get; set; }
        public Nullable<double> PlanBal { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public Nullable<int> Gw { get; set; }
    }
}
