//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorxLogisticsAPIs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrx_Countries
    {
        public string Image { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Continent { get; set; }
    
        public virtual Wrx_Continents Wrx_Continents { get; set; }
    }
}
